### PR TITLE
Sac 16 - setup the project

### PR DESCRIPTION
**Pull request by hjvvoorthuijsen**
# What
Setup the project with:
- vue
- vanillajs

# How to test
- run `npm run update`
- run `npm run start`

### CODE REVIEW

**Comment by sean-ww** [comment]
The vue todo app doesn't work

director.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
vue.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
director.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
vue.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:22 Uncaught ReferenceError: Vue is not defined
    at app.js:22
    at app.js:125
routes.js:22 Uncaught ReferenceError: app is not defined
    at routes.js:22

**Comment by sean-ww** [comment]
You could also just use 'npm start' and 'npm stop' without needing the run part.

**Comment by hjvvoorthuijsen** [comment]
@sean-ww Did you run `npm run update` ?
When I run that everything is working just fine

**Comment by sean-ww** [comment]
> @sean-ww Did you run `npm run update` ?
> When I run that everything is working just fine

I believe so, it was only one of the two that wasn't working. Both are working now, so I cannot reproduce.

**Pull request merged**
